'use client';

import { useEffect, useMemo, useState } from 'react';
import api from '@/lib/api';
import { Event } from '@/types';
import {
  HiOutlineCalendar,
  HiOutlineCheckCircle,
  HiOutlineClipboardCopy,
  HiOutlineRefresh,
  HiOutlineSparkles,
  HiOutlineTag,
  HiOutlineTicket,
  HiOutlineXCircle,
} from 'react-icons/hi';
import toast from 'react-hot-toast';

type SpecialCode = {
  id: string;
  code: string;
  ownerUserId: string;
  eventId: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  event?: Event | null;
};

type Props = {
  lang: 'es' | 'en';
};

export default function MySpecialCodesPanel({ lang }: Props) {
  const [codes, setCodes] = useState<SpecialCode[]>([]);
  const [loading, setLoading] = useState(true);

  const copy = {
    title: lang === 'es' ? 'Mis códigos especiales' : 'My special codes',
    subtitle: lang === 'es'
      ? 'Consulta los códigos rastreables que el equipo de LP Ticket te asignó.'
      : 'View the trackable codes assigned to you by the LP Ticket team.',
    emptyTitle: lang === 'es' ? 'Aún no tienes códigos asignados' : 'No codes assigned yet',
    emptyText: lang === 'es'
      ? 'Cuando un administrador te asigne un código, lo verás aquí.'
      : 'When an admin assigns you a code, you will see it here.',
    allEvents: lang === 'es' ? 'Todos los eventos' : 'All events',
    total: lang === 'es' ? 'Total' : 'Total',
    active: lang === 'es' ? 'Activos' : 'Active',
    eventCodes: lang === 'es' ? 'Por evento' : 'Event codes',
    activeLabel: lang === 'es' ? 'Activo' : 'Active',
    inactiveLabel: lang === 'es' ? 'Inactivo' : 'Inactive',
    copied: lang === 'es' ? 'Código copiado' : 'Code copied',
    copyButton: lang === 'es' ? 'Copiar código' : 'Copy code',
    refresh: lang === 'es' ? 'Actualizar' : 'Refresh',
    salesSoon: lang === 'es'
      ? 'Las ventas generadas por código aparecerán aquí cuando se active el rastreo en checkout.'
      : 'Sales generated by code will appear here when checkout tracking is enabled.',
    error: lang === 'es' ? 'No se pudieron cargar tus códigos.' : 'Could not load your codes.',
  };

  const loadCodes = async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/special-codes/me');
      setCodes(Array.isArray(data) ? data : []);
    } catch (err: any) {
      toast.error(err.response?.data?.message || copy.error);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadCodes();
  }, []);

  const stats = useMemo(() => {
    return {
      total: codes.length,
      active: codes.filter((item) => item.isActive).length,
      eventCodes: codes.filter((item) => Boolean(item.eventId)).length,
    };
  }, [codes]);

  const handleCopy = async (code: string) => {
    try {
      await navigator.clipboard.writeText(code);
      toast.success(copy.copied);
    } catch {
      toast.error(copy.error);
    }
  };

  return (
    <div className="space-y-5">
      <div className="dashboard-premium-card overflow-hidden">
        <div className="p-5 md:p-6 border-b border-gray-100 flex flex-col xl:flex-row xl:items-center xl:justify-between gap-5">
          <div className="flex items-start gap-3">
            <div className="public-premium-icon w-11 h-11 shrink-0 flex items-center justify-center">
              <HiOutlineTag className="w-5 h-5" />
            </div>
            <div>
              <p className="text-xs font-black uppercase tracking-[0.2em] text-primary-500">LP Ticket</p>
              <h2 className="text-xl font-black text-[#0A375A] mt-1">{copy.title}</h2>
              <p className="text-sm text-gray-500 mt-1 max-w-2xl">{copy.subtitle}</p>
            </div>
          </div>
          <button
            onClick={loadCodes}
            disabled={loading}
            className="btn-secondary inline-flex items-center justify-center gap-2 px-4 py-3 rounded-lg text-sm font-bold"
          >
            <HiOutlineRefresh className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
            {copy.refresh}
          </button>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3 p-5 md:p-6 border-b border-gray-100">
          <div className="rounded-lg border border-gray-100 bg-white p-4">
            <div className="flex items-center justify-between">
              <p className="text-xs font-black uppercase tracking-[0.18em] text-gray-400">{copy.total}</p>
              <HiOutlineTag className="w-5 h-5 text-primary-500" />
            </div>
            <p className="text-3xl font-black text-[#0A375A] mt-2">{stats.total}</p>
          </div>
          <div className="rounded-lg border border-gray-100 bg-white p-4">
            <div className="flex items-center justify-between">
              <p className="text-xs font-black uppercase tracking-[0.18em] text-gray-400">{copy.active}</p>
              <HiOutlineCheckCircle className="w-5 h-5 text-green-500" />
            </div>
            <p className="text-3xl font-black text-[#0A375A] mt-2">{stats.active}</p>
          </div>
          <div className="rounded-lg border border-gray-100 bg-white p-4">
            <div className="flex items-center justify-between">
              <p className="text-xs font-black uppercase tracking-[0.18em] text-gray-400">{copy.eventCodes}</p>
              <HiOutlineTicket className="w-5 h-5 text-primary-500" />
            </div>
            <p className="text-3xl font-black text-[#0A375A] mt-2">{stats.eventCodes}</p>
          </div>
        </div>

        {loading ? (
          <div className="p-5 space-y-3">
            {[...Array(3)].map((_, index) => (
              <div key={index} className="h-24 skeleton rounded-xl" />
            ))}
          </div>
        ) : codes.length === 0 ? (
          <div className="p-10 text-center">
            <HiOutlineSparkles className="w-12 h-12 text-gray-300 mx-auto" />
            <h3 className="text-lg font-black text-gray-900 mt-4">{copy.emptyTitle}</h3>
            <p className="text-sm text-gray-500 mt-2 max-w-md mx-auto">{copy.emptyText}</p>
          </div>
        ) : (
          <div className="divide-y divide-gray-100">
            {codes.map((item) => (
              <div key={item.id} className="p-5 md:p-6 flex flex-col lg:flex-row lg:items-center lg:justify-between gap-4">
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="text-3xl font-black tracking-wide text-[#0A375A]">{item.code}</p>
                    <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-black ${
                      item.isActive ? 'bg-green-50 text-green-700' : 'bg-gray-100 text-gray-500'
                    }`}>
                      {item.isActive ? <HiOutlineCheckCircle className="w-4 h-4" /> : <HiOutlineXCircle className="w-4 h-4" />}
                      {item.isActive ? copy.activeLabel : copy.inactiveLabel}
                    </span>
                  </div>
                  <p className="text-sm text-gray-500 mt-3 flex items-center gap-2">
                    <HiOutlineCalendar className="w-4 h-4 text-gray-400" />
                    {item.event?.title || copy.allEvents}
                  </p>
                </div>

                <button
                  onClick={() => handleCopy(item.code)}
                  className="btn-primary inline-flex items-center justify-center gap-2 px-5 py-3 rounded-lg text-sm font-black"
                >
                  <HiOutlineClipboardCopy className="w-5 h-5" />
                  {copy.copyButton}
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      {codes.length > 0 && (
        <div className="dashboard-premium-card p-5 md:p-6 flex items-start gap-3">
          <div className="public-premium-icon w-10 h-10 shrink-0 flex items-center justify-center">
            <HiOutlineSparkles className="w-5 h-5" />
          </div>
          <p className="text-sm font-semibold text-gray-600 leading-relaxed">{copy.salesSoon}</p>
        </div>
      )}
    </div>
  );
}
