'use client';

import { useEffect, useMemo, useState } from 'react';
import api from '@/lib/api';
import { Event } from '@/types';
import {
  HiOutlineCalendar,
  HiOutlineCheckCircle,
  HiOutlineClipboardCopy,
  HiOutlineCurrencyDollar,
  HiOutlineRefresh,
  HiOutlineShoppingCart,
  HiOutlineSparkles,
  HiOutlineTag,
  HiOutlineTicket,
  HiOutlineXCircle,
} from 'react-icons/hi';
import toast from 'react-hot-toast';
import { format } from 'date-fns';
import { es, enUS } from 'date-fns/locale';
import { parseSafeDate } from '@/lib/dateUtils';

type SpecialCode = {
  id: string;
  code: string;
  ownerUserId: string;
  eventId: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
  event?: Event | null;
};

type CodeSale = {
  id: string;
  specialCode: string;
  total: number;
  subtotal: number;
  ticketCount: number;
  paidAt: string | null;
  createdAt: string;
  event?: { title: string; currency?: string } | null;
  user?: { firstName: string; lastName: string; email: string } | null;
};

type PayoutSummary = {
  eventId: string;
  eventTitle: string;
  totalTickets: number;
  totalEarned: number;
  totalPaid: number;
  balance: number;
  codes: { code: string; commissionFixed: number; eventTitle: string | null }[];
  payouts: { id: string; amount: number; note: string | null; paidAt: string }[];
};

type Props = {
  lang: 'es' | 'en';
};

export default function MySpecialCodesPanel({ lang }: Props) {
  const [codes, setCodes] = useState<SpecialCode[]>([]);
  const [sales, setSales] = useState<CodeSale[]>([]);
  const [payouts, setPayouts] = useState<PayoutSummary[]>([]);
  const [loading, setLoading] = useState(true);
  const [salesLoading, setSalesLoading] = useState(true);
  const [payoutsLoading, setPayoutsLoading] = useState(true);

  const copy = {
    title: lang === 'es' ? 'Mis códigos especiales' : 'My special codes',
    subtitle: lang === 'es'
      ? 'Consulta los códigos rastreables que el equipo de LP Ticket te asignó.'
      : 'View the trackable codes assigned to you by the LP Ticket team.',
    emptyTitle: lang === 'es' ? 'Aún no tienes códigos asignados' : 'No codes assigned yet',
    emptyText: lang === 'es'
      ? 'Cuando un administrador te asigne un código, lo verás aquí.'
      : 'When an admin assigns you a code, you will see it here.',
    allEvents: lang === 'es' ? 'Todos los eventos' : 'All events',
    total: lang === 'es' ? 'Total' : 'Total',
    active: lang === 'es' ? 'Activos' : 'Active',
    eventCodes: lang === 'es' ? 'Por evento' : 'Event codes',
    activeLabel: lang === 'es' ? 'Activo' : 'Active',
    inactiveLabel: lang === 'es' ? 'Inactivo' : 'Inactive',
    copied: lang === 'es' ? 'Código copiado' : 'Code copied',
    copyButton: lang === 'es' ? 'Copiar código' : 'Copy code',
    refresh: lang === 'es' ? 'Actualizar' : 'Refresh',
    salesTitle: lang === 'es' ? 'Ventas generadas por mis códigos' : 'Sales generated by my codes',
    salesEmpty: lang === 'es' ? 'Aún no hay ventas con tus códigos.' : 'No sales yet with your codes.',
    salesCode: lang === 'es' ? 'Código' : 'Code',
    salesEvent: lang === 'es' ? 'Evento' : 'Event',
    salesBuyer: lang === 'es' ? 'Comprador' : 'Buyer',
    salesDate: lang === 'es' ? 'Fecha' : 'Date',
    salesTotal: lang === 'es' ? 'Total' : 'Total',
    salesTickets: lang === 'es' ? 'Entradas' : 'Tickets',
    payoutsTitle: lang === 'es' ? 'Mis recompensas por evento' : 'My rewards by event',
    payoutsEmpty: lang === 'es' ? 'Aún no tienes recompensas generadas.' : 'No rewards generated yet.',
    earned: lang === 'es' ? 'Ganado' : 'Earned',
    paid: lang === 'es' ? 'Pagado' : 'Paid',
    balance: lang === 'es' ? 'Saldo' : 'Balance',
    paymentHistory: lang === 'es' ? 'Historial de pagos' : 'Payment history',
    error: lang === 'es' ? 'No se pudieron cargar tus códigos.' : 'Could not load your codes.',
  };

  const loadCodes = async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/special-codes/me');
      setCodes(Array.isArray(data) ? data : []);
    } catch (err: any) {
      toast.error(err.response?.data?.message || copy.error);
    } finally {
      setLoading(false);
    }
  };

  const loadSales = async () => {
    setSalesLoading(true);
    try {
      const { data } = await api.get('/special-codes/my-sales');
      setSales(Array.isArray(data) ? data : []);
    } catch {
      // Sales endpoint may return empty — fail silently
    } finally {
      setSalesLoading(false);
    }
  };

  const loadPayouts = async () => {
    setPayoutsLoading(true);
    try {
      const { data } = await api.get('/special-codes/my-payouts');
      setPayouts(Array.isArray(data) ? data : []);
    } catch {
      // Payouts can be empty for creators without sales yet.
    } finally {
      setPayoutsLoading(false);
    }
  };

  useEffect(() => {
    loadCodes();
    loadSales();
    loadPayouts();
  }, []);

  const stats = useMemo(() => {
    return {
      total: codes.length,
      active: codes.filter((item) => item.isActive).length,
      eventCodes: codes.filter((item) => Boolean(item.eventId)).length,
      totalEarned: payouts.reduce((sum, item) => sum + Number(item.totalEarned || 0), 0),
      totalPaid: payouts.reduce((sum, item) => sum + Number(item.totalPaid || 0), 0),
      balance: payouts.reduce((sum, item) => sum + Number(item.balance || 0), 0),
    };
  }, [codes, payouts]);

  const handleCopy = async (code: string) => {
    try {
      await navigator.clipboard.writeText(code);
      toast.success(copy.copied);
    } catch {
      toast.error(copy.error);
    }
  };

  return (
    <div className="space-y-5">
      <div className="dashboard-premium-card overflow-hidden">
        <div className="p-5 md:p-6 border-b border-gray-100 flex flex-col xl:flex-row xl:items-center xl:justify-between gap-5">
          <div className="flex items-start gap-3">
            <div className="public-premium-icon w-11 h-11 shrink-0 flex items-center justify-center">
              <HiOutlineTag className="w-5 h-5" />
            </div>
            <div>
              <p className="text-xs font-black uppercase tracking-[0.2em] text-primary-500">LP Ticket</p>
              <h2 className="text-xl font-black text-[#0A375A] mt-1 leading-tight">{copy.title}</h2>
              <p className="text-sm text-gray-500 mt-1 max-w-2xl">{copy.subtitle}</p>
            </div>
          </div>
          <button
            onClick={loadCodes}
            disabled={loading}
            className="btn-secondary inline-flex items-center justify-center gap-2 px-4 py-3 rounded-lg text-sm font-bold"
          >
            <HiOutlineRefresh className={`w-5 h-5 ${loading ? 'animate-spin' : ''}`} />
            {copy.refresh}
          </button>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-6 gap-2.5 p-4 md:p-5 border-b border-gray-100">
          <div className="rounded-lg border border-gray-100 bg-white p-3 min-h-[88px] flex flex-col justify-between">
            <div className="flex items-center justify-between">
              <p className="text-[10px] font-black uppercase tracking-[0.12em] text-gray-400 leading-tight">{copy.total}</p>
              <HiOutlineTag className="w-5 h-5 text-primary-500" />
            </div>
            <p className="text-2xl font-black text-[#0A375A] mt-1 tabular-nums leading-none">{stats.total}</p>
          </div>
          <div className="rounded-lg border border-gray-100 bg-white p-3 min-h-[88px] flex flex-col justify-between">
            <div className="flex items-center justify-between">
              <p className="text-[10px] font-black uppercase tracking-[0.12em] text-gray-400 leading-tight">{copy.active}</p>
              <HiOutlineCheckCircle className="w-5 h-5 text-green-500" />
            </div>
            <p className="text-2xl font-black text-[#0A375A] mt-1 tabular-nums leading-none">{stats.active}</p>
          </div>
          <div className="rounded-lg border border-gray-100 bg-white p-3 min-h-[88px] flex flex-col justify-between">
            <div className="flex items-center justify-between">
              <p className="text-[10px] font-black uppercase tracking-[0.08em] text-gray-400 leading-tight">{copy.eventCodes}</p>
              <HiOutlineTicket className="w-5 h-5 text-primary-500" />
            </div>
            <p className="text-2xl font-black text-[#0A375A] mt-1 tabular-nums leading-none">{stats.eventCodes}</p>
          </div>
          <div className="rounded-lg border border-gray-100 bg-white p-3 min-h-[88px] flex flex-col justify-between">
            <p className="text-[10px] font-black uppercase tracking-[0.12em] text-gray-400 leading-tight">{copy.earned}</p>
            <p className="text-xl font-black text-[#0A375A] mt-1 tabular-nums leading-none">${stats.totalEarned.toFixed(2)}</p>
          </div>
          <div className="rounded-lg border border-gray-100 bg-white p-3 min-h-[88px] flex flex-col justify-between">
            <p className="text-[10px] font-black uppercase tracking-[0.12em] text-gray-400 leading-tight">{copy.paid}</p>
            <p className="text-xl font-black text-green-600 mt-1 tabular-nums leading-none">${stats.totalPaid.toFixed(2)}</p>
          </div>
          <div className="rounded-lg border border-gray-100 bg-white p-3 min-h-[88px] flex flex-col justify-between">
            <p className="text-[10px] font-black uppercase tracking-[0.12em] text-gray-400 leading-tight">{copy.balance}</p>
            <p className="text-xl font-black text-primary-500 mt-1 tabular-nums leading-none">${stats.balance.toFixed(2)}</p>
          </div>
        </div>

        {loading ? (
          <div className="p-5 space-y-3">
            {[...Array(3)].map((_, index) => (
              <div key={index} className="h-24 skeleton rounded-xl" />
            ))}
          </div>
        ) : codes.length === 0 ? (
          <div className="p-10 text-center">
            <HiOutlineSparkles className="w-12 h-12 text-gray-300 mx-auto" />
            <h3 className="text-lg font-black text-gray-900 mt-4">{copy.emptyTitle}</h3>
            <p className="text-sm text-gray-500 mt-2 max-w-md mx-auto">{copy.emptyText}</p>
          </div>
        ) : (
          <div className="divide-y divide-white/[0.05]">
            {codes.map((item) => (
              <div key={item.id} className="p-4 md:p-5 grid grid-cols-1 sm:grid-cols-[minmax(0,1fr)_auto] sm:items-center gap-3">
                <div className="min-w-0">
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="text-xl sm:text-2xl font-black tracking-wide text-[#0A375A] break-all leading-tight">{item.code}</p>
                    <span className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs font-black ${
                      item.isActive ? 'bg-green-50 text-green-700' : 'bg-gray-100 text-gray-500'
                    }`}>
                      {item.isActive ? <HiOutlineCheckCircle className="w-4 h-4" /> : <HiOutlineXCircle className="w-4 h-4" />}
                      {item.isActive ? copy.activeLabel : copy.inactiveLabel}
                    </span>
                  </div>
                  <p className="text-xs sm:text-sm text-gray-500 mt-2 flex items-center gap-2 min-w-0">
                    <HiOutlineCalendar className="w-4 h-4 text-gray-400" />
                    {item.event?.title || copy.allEvents}
                  </p>
                </div>

                <button
                  onClick={() => handleCopy(item.code)}
                  className="btn-secondary inline-flex items-center justify-center gap-2 px-4 py-2.5 rounded-lg text-xs font-black w-full sm:w-auto whitespace-nowrap border-orange-200 text-orange-600 hover:bg-orange-50"
                >
                  <HiOutlineClipboardCopy className="w-5 h-5" />
                  {copy.copyButton}
                </button>
              </div>
            ))}
          </div>
        )}
      </div>

      {codes.length > 0 && (
        <div className="dashboard-premium-card overflow-hidden">
          <div className="p-5 md:p-6 border-b border-gray-100 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="public-premium-icon w-10 h-10 shrink-0 flex items-center justify-center">
                <HiOutlineCurrencyDollar className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-black text-[#0A375A]">{copy.payoutsTitle}</h3>
                {payouts.length > 0 && (
                  <p className="text-xs text-gray-400 mt-0.5">
                    {copy.earned}: ${stats.totalEarned.toFixed(2)} · {copy.paid}: ${stats.totalPaid.toFixed(2)} · {copy.balance}: ${stats.balance.toFixed(2)}
                  </p>
                )}
              </div>
            </div>
            <button
              onClick={loadPayouts}
              disabled={payoutsLoading}
              className="btn-secondary inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-bold"
            >
              <HiOutlineRefresh className={`w-4 h-4 ${payoutsLoading ? 'animate-spin' : ''}`} />
              {copy.refresh}
            </button>
          </div>

          {payoutsLoading ? (
            <div className="p-5 space-y-3">
              {[...Array(2)].map((_, i) => <div key={i} className="h-24 skeleton rounded-lg" />)}
            </div>
          ) : payouts.length === 0 ? (
            <div className="p-10 text-center">
              <HiOutlineCurrencyDollar className="w-10 h-10 text-gray-300 mx-auto" />
              <p className="text-sm text-gray-400 mt-3 font-medium">{copy.payoutsEmpty}</p>
            </div>
          ) : (
            <div className="divide-y divide-white/[0.05]">
              {payouts.map((item) => (
                <div key={`${item.eventId}-${item.codes.map((code) => code.code).join('-')}`} className="p-5 md:p-6 space-y-4">
                  <div className="grid grid-cols-1 lg:grid-cols-[minmax(0,1fr)_auto] lg:items-center gap-4">
                    <div>
                      <p className="font-black text-gray-900">{item.eventTitle}</p>
                      <div className="flex flex-wrap gap-1.5 mt-2">
                        {item.codes.map((code) => (
                          <span key={code.code} className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-gray-100 text-xs font-bold text-gray-600">
                            {code.code} · ${Number(code.commissionFixed || 0).toFixed(2)}
                          </span>
                        ))}
                      </div>
                    </div>
                    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4 text-left sm:text-right">
                      <div>
                        <p className="text-xs font-black uppercase text-gray-400">{copy.salesTickets}</p>
                        <p className="text-lg font-black text-gray-900 tabular-nums">{item.totalTickets}</p>
                      </div>
                      <div>
                        <p className="text-xs font-black uppercase text-gray-400">{copy.earned}</p>
                        <p className="text-lg font-black text-[#0A375A] tabular-nums">${Number(item.totalEarned || 0).toFixed(2)}</p>
                      </div>
                      <div>
                        <p className="text-xs font-black uppercase text-gray-400">{copy.paid}</p>
                        <p className="text-lg font-black text-green-600 tabular-nums">${Number(item.totalPaid || 0).toFixed(2)}</p>
                      </div>
                      <div>
                        <p className="text-xs font-black uppercase text-gray-400">{copy.balance}</p>
                        <p className="text-lg font-black text-primary-500 tabular-nums">${Number(item.balance || 0).toFixed(2)}</p>
                      </div>
                    </div>
                  </div>

                  {item.payouts.length > 0 && (
                    <div className="rounded-xl bg-gray-50 p-3 space-y-1.5 overflow-hidden">
                      <p className="text-xs font-black uppercase tracking-wider text-gray-400">{copy.paymentHistory}</p>
                      {item.payouts.map((payment) => (
                        <div key={payment.id} className="flex items-center justify-between gap-3 text-xs">
                          <span className="text-gray-500">
                            {new Date(payment.paidAt).toLocaleDateString(lang === 'es' ? 'es-US' : 'en-US')}{payment.note ? ` · ${payment.note}` : ''}
                          </span>
                          <span className="font-black text-green-700">${Number(payment.amount || 0).toFixed(2)}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {codes.length > 0 && (
        <div className="dashboard-premium-card overflow-hidden">
          <div className="p-5 md:p-6 border-b border-gray-100 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="public-premium-icon w-10 h-10 shrink-0 flex items-center justify-center">
                <HiOutlineShoppingCart className="w-5 h-5" />
              </div>
              <div>
                <h3 className="font-black text-[#0A375A]">{copy.salesTitle}</h3>
                {sales.length > 0 && (
                  <p className="text-xs text-gray-400 mt-0.5">
                    {sales.length} {lang === 'es' ? 'venta(s)' : 'sale(s)'} · Total: $
                    {sales.reduce((s, o) => s + Number(o.total || 0), 0).toFixed(2)}
                  </p>
                )}
              </div>
            </div>
            <button
              onClick={loadSales}
              disabled={salesLoading}
              className="btn-secondary inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-xs font-bold"
            >
              <HiOutlineRefresh className={`w-4 h-4 ${salesLoading ? 'animate-spin' : ''}`} />
              {copy.refresh}
            </button>
          </div>

          {salesLoading ? (
            <div className="p-5 space-y-3">
              {[...Array(3)].map((_, i) => <div key={i} className="h-14 skeleton rounded-lg" />)}
            </div>
          ) : sales.length === 0 ? (
            <div className="p-10 text-center">
              <HiOutlineCurrencyDollar className="w-10 h-10 text-gray-300 mx-auto" />
              <p className="text-sm text-gray-400 mt-3 font-medium">{copy.salesEmpty}</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-sm">
                <thead>
                  <tr className="bg-gray-50 border-b border-gray-100">
                    <th className="text-left px-5 py-3 text-xs font-black uppercase tracking-wider text-gray-400">{copy.salesCode}</th>
                    <th className="text-left px-5 py-3 text-xs font-black uppercase tracking-wider text-gray-400">{copy.salesEvent}</th>
                    <th className="text-left px-5 py-3 text-xs font-black uppercase tracking-wider text-gray-400 hidden md:table-cell">{copy.salesBuyer}</th>
                    <th className="text-left px-5 py-3 text-xs font-black uppercase tracking-wider text-gray-400 hidden sm:table-cell">{copy.salesDate}</th>
                    <th className="text-right px-5 py-3 text-xs font-black uppercase tracking-wider text-gray-400">{copy.salesTickets}</th>
                    <th className="text-right px-5 py-3 text-xs font-black uppercase tracking-wider text-gray-400">{copy.salesTotal}</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-white/[0.05]">
                  {sales.map((sale) => (
                    <tr key={sale.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-5 py-3.5">
                        <span className="font-mono font-black text-[#F97316] text-xs">{sale.specialCode}</span>
                      </td>
                      <td className="px-5 py-3.5">
                        <span className="font-semibold text-gray-800 text-xs truncate max-w-[140px] block">{sale.event?.title || '—'}</span>
                      </td>
                      <td className="px-5 py-3.5 hidden md:table-cell">
                        <span className="text-xs text-gray-500">
                          {sale.user ? `${sale.user.firstName} ${sale.user.lastName}` : '—'}
                        </span>
                      </td>
                      <td className="px-5 py-3.5 hidden sm:table-cell">
                        <span className="text-xs text-gray-400">
                          {sale.paidAt
                            ? format(parseSafeDate(sale.paidAt), 'dd MMM yyyy', { locale: lang === 'es' ? es : enUS })
                            : format(parseSafeDate(sale.createdAt), 'dd MMM yyyy', { locale: lang === 'es' ? es : enUS })}
                        </span>
                      </td>
                      <td className="px-5 py-3.5 text-right">
                        <span className="text-xs font-semibold text-gray-700">{sale.ticketCount}</span>
                      </td>
                      <td className="px-5 py-3.5 text-right">
                        <span className="font-black text-[#0A375A] text-sm">${Number(sale.total).toFixed(2)}</span>
                        <span className="text-[10px] text-gray-400 ml-1">{sale.event?.currency || 'USD'}</span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
