'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Lang = 'es' | 'en';

const translations = {
  es: {
    // Navbar
    whoWeAre: 'Quiéne Somos',
    contact: 'Contacto',
    support: 'Soporte',
    login: 'INICIAR SESIÓN',
    register: 'REGISTRARSE',
    myProfile: 'Mi Perfil',
    myTickets: 'Mis Tickets',
    organizerPanel: 'Panel Organizador',
    buyerMode: 'Modo Comprador',
    organizerMode: 'Modo Organizador',
    logout: 'Cerrar Sesión',

    searchPlaceholder: '¿Cómo te quieres divertir hoy?',
    searchMobile: 'Buscar eventos...',
    events: 'Eventos',

    // Homepage
    sortBy: 'Ordenar por',
    categories: 'Categorías',
    date: 'Fecha',
    price: 'Precio',
    buyTickets: 'COMPRAR TICKETS',
    demoNotice: '📋 Mostrando eventos de demostración. Conecta la base de datos para ver eventos reales.',
    noEventsCategory: 'No hay eventos en esta categoría',

    // Login
    loginTitle: 'Iniciar Sesión',
    loginSubtitle: 'Accede a tu cuenta de LPTicket',
    email: 'Correo electrónico',
    password: 'Contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    loginBtn: 'INICIAR SESIÓN',
    loginLoading: 'Iniciando sesión...',
    noAccount: '¿No tienes cuenta?',
    registerFree: 'Regístrate gratis',

    // Register
    registerTitle: 'Registro',
    registerSubtitle: 'Únete a LPTicket',
    organizerSubtitle: 'Registra tu cuenta de organizador',
    buyer: '🎫 Comprador',
    organizer: '🎪 Organizador',
    username: 'Usuario',
    idType: 'Tipo',
    idNumber: 'Identificación',
    firstName: 'Nombre',
    lastName: 'Apellido',
    phone: 'Teléfono',
    address: 'Dirección',
    confirmPassword: 'Contraseña (de nuevo)',
    captcha: 'Captcha',
    captchaError: 'Captcha incorrecto, intenta de nuevo',
    passwordMismatch: 'Las contraseñas no coinciden',
    createAccount: 'CREAR CUENTA',
    creating: 'Creando cuenta...',
    haveAccount: '¿Ya tienes una cuenta?',
    signIn: 'Inicia sesión',
    orContinueWith: 'O CONTINUAR CON',
    refresh: 'Refrescar',
    clickToRefresh: 'Clic para refrescar',
    enterCode: 'Escribe el código',
    firstNamePlaceholder: 'Juan',
    lastNamePlaceholder: 'Pérez',
    emailPlaceholder: 'correo@ejemplo.com',
    phonePlaceholder: '+1 (555) 000-0000',
    addressPlaceholder: 'Calle, Ciudad, Estado, ZIP',

    // Errors
    registerError: 'Error al registrarse',
    loginError: 'Error al iniciar sesión',

    // Footer
    terms: 'Términos Legales',
    pointsOfSale: 'Puntos de Venta',
    myAccount: 'Mi Cuenta',
    copyright: 'Todos los derechos reservados.',

    // Categories
    catTheater: 'Teatro',
    catConcert: 'Concierto',
    catConference: 'Conferencia',
    catSports: 'Deporte',
    catKids: 'Infantil',
    catFestival: 'Festival',
    catComedy: 'Comedia',
    catOther: 'Otro',
    catAll: 'Todas',

    // About Us
    aboutTitle: 'Sobre nosotros',
    aboutText1: 'LPTicket es una marca registrada con amplia experiencia en el mercado, creada con el objetivo de suministrar a través de nuestro portal web un sistema de boletería seguro que permite la venta en línea y en puntos físicos, tickets para todo tipo de eventos. Al productor le ofrecemos un servicio administrativo integral con el que planifica, distribuye, controla y visualiza la boletería de su evento.',
    aboutMissionTitle: 'Nuestra misión',
    aboutMissionText: 'Ofrecer un servicio de boletería seguro y de calidad a nivel nacional, proporcionando diversos medios de pago que faciliten al cliente el acceso rápido al ticket. Ofrecer Atención de calidad en nuestros puntos de venta y sitio en línea, generando una experiencia de compra agradable que origine satisfacción, lealtad y confianza en el usuario, cliente y productor.',
    aboutVisionTitle: 'Nuestra visión',
    aboutVisionText: 'Ser la empresa de boletería líder en el ramo, combinando la inversión constante en nuevas tecnologías con los cambios que impone el mercado, abarcando otras áreas de interés que generen satisfacción plena al usuario, cliente y productor. Siempre forjando valores institucionales que mantengan firme el sentido de pertenencia de nuestro equipo y permitan ser transmitidos al público externo.',

    // Contact
    contactPageTitle: 'Contacto',
    contactSubtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    contactOnline: 'Contacto en línea',
    contactAddress: 'Nuestra dirección',
    contactAddressText1: '123 Lorem Ipsum Street',
    contactAddressText2: 'Fake City, 12345, Lorem Ipsum Country.',
    contactEmailTitle: 'E-mail',
    contactEmail: 'Info.lpticket@gmail.com',
    contactPhone: '+1 (555) 123-4567',
    contactFollowUs: '¡Síguenos en nuestras redes sociales!',

    // Organizer Panel
    orgPanel: 'Panel de Organizador',
    orgDashboard: 'Dashboard',
    orgMyEvents: 'Mis Eventos',
    orgCreateEvent: 'Crear Evento',
    orgAttendees: 'Asistentes',
    orgSales: 'Ventas',
    orgSettings: 'Configuración',
    orgWelcome: 'Bienvenido',
    orgManageEvents: 'Gestiona tus eventos y visualiza tus métricas',
    orgTotalRevenue: 'Ingresos Totales',
    orgTicketsSold: 'Tickets Vendidos',
    orgActiveEvents: 'Eventos Activos',
    orgTotalOrders: 'Órdenes Totales',
    orgRecentEvents: 'Eventos Recientes',
    orgViewAll: 'Ver todos',
    orgNoEvents: 'Aún no has creado ningún evento',
    orgCreateFirst: 'Crear mi primer evento',
    orgEventTitle: 'Título del Evento',
    orgEventDesc: 'Descripción',
    orgCategory: 'Categoría',
    orgVenue: 'Lugar / Venue',
    orgVenueAddress: 'Dirección del Venue',
    orgEventDate: 'Fecha del Evento',
    orgDoorsOpen: 'Apertura de Puertas',
    orgSectionName: 'Nombre de Sección',
    orgSectionType: 'Tipo de Sección',
    orgSeated: 'Con Asientos',
    orgStanding: 'General (De Pie)',
    orgVIP: 'VIP',
    orgRows: 'Filas',
    orgSeatsPerRow: 'Asientos/Fila',
    orgPrice: 'Precio (USD)',
    orgAddSection: 'Agregar Sección',
    orgRemoveSection: 'Quitar',
    orgCreateEventBtn: 'CREAR EVENTO',
    orgCreating: 'Creando...',
    orgCancel: 'Cancelar',
    orgPublish: 'Publicar',
    orgSendApproval: 'Enviar a Aprobación',
    orgDraft: 'Borrador',
    orgPending: 'Pendiente',
    orgPublished: 'Publicado',
    orgCancelled: 'Cancelado',
    orgCompleted: 'Completado',
    orgEditEvent: 'Editar Evento',
    orgDeleteEvent: 'Eliminar Evento',
    orgViewSales: 'Ver Ventas',
    orgExportCSV: 'Exportar CSV',
    orgRevenue: 'Ingresos',
    orgTickets: 'Tickets',
    orgOrders: 'Órdenes',
    orgAttendeeName: 'Nombre',
    orgAttendeeEmail: 'Email',
    orgAttendeeSection: 'Sección',
    orgAttendeeRow: 'Fila',
    orgAttendeeSeat: 'Asiento',
    orgAttendeeCode: 'Código',
    orgAttendeeStatus: 'Estado',
    orgBackToDashboard: 'Volver al Dashboard',
    orgSections: 'Secciones',
    orgEventImage: 'Imagen del Evento',
    orgUploadImage: 'Subir Imagen',
    orgCapacity: 'Capacidad',

    // Admin Panel
    adminPanel: 'Panel de Administración',
    adminDashboard: 'Dashboard',
    adminEvents: 'Eventos',
    adminUsers: 'Usuarios',
    adminOrders: 'Órdenes',
    adminTotalUsers: 'Usuarios Totales',
    adminTotalEvents: 'Eventos Totales',
    adminTotalRevenue: 'Ingresos Totales',
    adminTotalOrders: 'Órdenes Totales',
    adminBuyers: 'Compradores',
    adminOrganizers: 'Organizadores',
    adminAdmins: 'Administradores',
    adminPublished: 'Publicados',
    adminDrafts: 'Borradores',
    adminApprove: 'Aprobar',
    adminReject: 'Rechazar',
    adminBlock: 'Bloquear',
    adminUnblock: 'Desbloquear',
    adminChangeRole: 'Cambiar Rol',
    adminAllEvents: 'Todos los Eventos',
    adminPendingApproval: 'Pendientes de Aprobación',
    adminUserManagement: 'Gestión de Usuarios',
    adminEventManagement: 'Gestión de Eventos',
    adminActive: 'Activo',
    adminInactive: 'Inactivo',
    adminRole: 'Rol',
    adminActions: 'Acciones',
    adminOrganizer: 'Organizador',
    adminNoUsers: 'No hay usuarios registrados',
    adminNoEvents: 'No hay eventos',
    adminNoOrders: 'No hay órdenes',
    adminTicketsSold: 'Tickets Vendidos',
    adminEventTitle: 'Evento',
    adminCategory: 'Categoría',
    adminDate: 'Fecha',

    // Client Dashboard
    clientHello: 'Hola',
    clientManage: 'Gestiona tus tickets y tu perfil',
    clientMyTickets: 'Mis Tickets',
    clientHistory: 'Historial',
    clientProfile: 'Perfil',
    clientNoTickets: 'No tienes tickets aún',
    clientExplore: 'Explorar eventos',
    clientNoOrders: 'No tienes compras aún',
    clientPersonalInfo: 'Información personal',
    clientEdit: 'Editar',
    clientSave: 'Guardar cambios',
    clientName: 'Nombre',
    clientLastName: 'Apellido',
    clientPhone: 'Teléfono',
    clientActive: 'Activo',
    clientUsed: 'Usado',
    clientCancelled: 'Cancelado',
    clientPaid: 'Pagado',
    clientPending: 'Pendiente',
    clientViewTicket: 'Ver ticket',
    clientSection: 'Sección',
    clientRow: 'Fila',
    clientSeat: 'Asiento',
    clientCode: 'Código',
  },
  en: {
    // Navbar
    whoWeAre: 'About Us',
    contact: 'Contact',
    support: 'Support',
    login: 'LOG IN',
    register: 'SIGN UP',
    myProfile: 'My Profile',
    myTickets: 'My Tickets',
    organizerPanel: 'Organizer Panel',
    buyerMode: 'Buyer Mode',
    organizerMode: 'Organizer Mode',
    logout: 'Log Out',

    searchPlaceholder: 'What do you want to do today?',
    searchMobile: 'Search events...',
    events: 'Events',

    // Homepage
    sortBy: 'Sort by',
    categories: 'Categories',
    date: 'Date',
    price: 'Price',
    buyTickets: 'BUY TICKETS',
    demoNotice: '📋 Showing demo events. Connect the database to see real events.',
    noEventsCategory: 'No events in this category',

    // Login
    loginTitle: 'Log In',
    loginSubtitle: 'Access your LPTicket account',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot your password?',
    loginBtn: 'LOG IN',
    loginLoading: 'Logging in...',
    noAccount: "Don't have an account?",
    registerFree: 'Sign up for free',

    // Register
    registerTitle: 'Sign Up',
    registerSubtitle: 'Join LPTicket',
    organizerSubtitle: 'Create your organizer account',
    buyer: '🎫 Buyer',
    organizer: '🎪 Organizer',
    username: 'Username',
    idType: 'Type',
    idNumber: 'ID Number',
    firstName: 'First Name',
    lastName: 'Last Name',
    phone: 'Phone Number',
    address: 'Address',
    confirmPassword: 'Confirm Password',
    captcha: 'Captcha',
    captchaError: 'Incorrect captcha, try again',
    passwordMismatch: 'Passwords do not match',
    createAccount: 'CREATE ACCOUNT',
    creating: 'Creating account...',
    haveAccount: 'Already have an account?',
    signIn: 'Sign in',
    orContinueWith: 'OR CONTINUE WITH',
    refresh: 'Refresh',
    clickToRefresh: 'Click to refresh',
    enterCode: 'Enter the code',
    firstNamePlaceholder: 'John',
    lastNamePlaceholder: 'Doe',
    emailPlaceholder: 'email@example.com',
    phonePlaceholder: '+1 (555) 000-0000',
    addressPlaceholder: 'Street, City, State, ZIP',

    // Errors
    registerError: 'Registration error',
    loginError: 'Login error',

    // Footer
    terms: 'Legal Terms',
    pointsOfSale: 'Points of Sale',
    myAccount: 'My Account',
    copyright: 'All rights reserved.',

    // Categories
    catTheater: 'Theater',
    catConcert: 'Concert',
    catConference: 'Conference',
    catSports: 'Sports',
    catKids: 'Kids',
    catFestival: 'Festival',
    catComedy: 'Comedy',
    catOther: 'Other',
    catAll: 'All',

    // About Us
    aboutTitle: 'About Us',
    aboutText1: 'LPTicket is a registered brand with extensive experience in the market, created with the objective of providing through our web portal a secure ticketing system that allows online and physical point-of-sale ticket distribution for all types of events. We offer producers a comprehensive administrative service to plan, distribute, control, and visualize their event ticketing.',
    aboutMissionTitle: 'Our Mission',
    aboutMissionText: 'To offer a secure and high-quality ticketing service nationwide, providing various payment methods that facilitate quick access to tickets for the customer. To offer quality customer service at our points of sale and online site, generating a pleasant shopping experience that creates satisfaction, loyalty, and trust in the user, client, and producer.',
    aboutVisionTitle: 'Our Vision',
    aboutVisionText: 'To be the leading ticketing company in the industry, combining constant investment in new technologies with market changes, covering other areas of interest that generate full satisfaction for the user, client, and producer. Always forging institutional values that keep our team\'s sense of belonging firm and allow it to be transmitted to the external public.',

    // Contact
    contactPageTitle: 'Contact',
    contactSubtitle: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    contactOnline: 'Online Contact',
    contactAddress: 'Our Address',
    contactAddressText1: '123 Lorem Ipsum Street',
    contactAddressText2: 'Fake City, 12345, Lorem Ipsum Country.',
    contactEmailTitle: 'E-mail',
    contactEmail: 'Info.lpticket@gmail.com',
    contactPhone: '+1 (555) 123-4567',
    contactFollowUs: 'Follow us on our social networks!',

    // Organizer Panel
    orgPanel: 'Organizer Panel',
    orgDashboard: 'Dashboard',
    orgMyEvents: 'My Events',
    orgCreateEvent: 'Create Event',
    orgAttendees: 'Attendees',
    orgSales: 'Sales',
    orgSettings: 'Settings',
    orgWelcome: 'Welcome',
    orgManageEvents: 'Manage your events and view your metrics',
    orgTotalRevenue: 'Total Revenue',
    orgTicketsSold: 'Tickets Sold',
    orgActiveEvents: 'Active Events',
    orgTotalOrders: 'Total Orders',
    orgRecentEvents: 'Recent Events',
    orgViewAll: 'View all',
    orgNoEvents: 'You haven\'t created any events yet',
    orgCreateFirst: 'Create my first event',
    orgEventTitle: 'Event Title',
    orgEventDesc: 'Description',
    orgCategory: 'Category',
    orgVenue: 'Venue',
    orgVenueAddress: 'Venue Address',
    orgEventDate: 'Event Date',
    orgDoorsOpen: 'Doors Open',
    orgSectionName: 'Section Name',
    orgSectionType: 'Section Type',
    orgSeated: 'Seated',
    orgStanding: 'General Admission',
    orgVIP: 'VIP',
    orgRows: 'Rows',
    orgSeatsPerRow: 'Seats/Row',
    orgPrice: 'Price (USD)',
    orgAddSection: 'Add Section',
    orgRemoveSection: 'Remove',
    orgCreateEventBtn: 'CREATE EVENT',
    orgCreating: 'Creating...',
    orgCancel: 'Cancel',
    orgPublish: 'Publish',
    orgSendApproval: 'Send for Approval',
    orgDraft: 'Draft',
    orgPending: 'Pending',
    orgPublished: 'Published',
    orgCancelled: 'Cancelled',
    orgCompleted: 'Completed',
    orgEditEvent: 'Edit Event',
    orgDeleteEvent: 'Delete Event',
    orgViewSales: 'View Sales',
    orgExportCSV: 'Export CSV',
    orgRevenue: 'Revenue',
    orgTickets: 'Tickets',
    orgOrders: 'Orders',
    orgAttendeeName: 'Name',
    orgAttendeeEmail: 'Email',
    orgAttendeeSection: 'Section',
    orgAttendeeRow: 'Row',
    orgAttendeeSeat: 'Seat',
    orgAttendeeCode: 'Code',
    orgAttendeeStatus: 'Status',
    orgBackToDashboard: 'Back to Dashboard',
    orgSections: 'Sections',
    orgEventImage: 'Event Image',
    orgUploadImage: 'Upload Image',
    orgCapacity: 'Capacity',

    // Admin Panel
    adminPanel: 'Admin Panel',
    adminDashboard: 'Dashboard',
    adminEvents: 'Events',
    adminUsers: 'Users',
    adminOrders: 'Orders',
    adminTotalUsers: 'Total Users',
    adminTotalEvents: 'Total Events',
    adminTotalRevenue: 'Total Revenue',
    adminTotalOrders: 'Total Orders',
    adminBuyers: 'Buyers',
    adminOrganizers: 'Organizers',
    adminAdmins: 'Admins',
    adminPublished: 'Published',
    adminDrafts: 'Drafts',
    adminApprove: 'Approve',
    adminReject: 'Reject',
    adminBlock: 'Block',
    adminUnblock: 'Unblock',
    adminChangeRole: 'Change Role',
    adminAllEvents: 'All Events',
    adminPendingApproval: 'Pending Approval',
    adminUserManagement: 'User Management',
    adminEventManagement: 'Event Management',
    adminActive: 'Active',
    adminInactive: 'Inactive',
    adminRole: 'Role',
    adminActions: 'Actions',
    adminOrganizer: 'Organizer',
    adminNoUsers: 'No registered users',
    adminNoEvents: 'No events',
    adminNoOrders: 'No orders',
    adminTicketsSold: 'Tickets Sold',
    adminEventTitle: 'Event',
    adminCategory: 'Category',
    adminDate: 'Date',

    // Client Dashboard
    clientHello: 'Hello',
    clientManage: 'Manage your tickets and profile',
    clientMyTickets: 'My Tickets',
    clientHistory: 'History',
    clientProfile: 'Profile',
    clientNoTickets: 'You don\'t have any tickets yet',
    clientExplore: 'Explore events',
    clientNoOrders: 'You don\'t have any orders yet',
    clientPersonalInfo: 'Personal Information',
    clientEdit: 'Edit',
    clientSave: 'Save changes',
    clientName: 'First Name',
    clientLastName: 'Last Name',
    clientPhone: 'Phone',
    clientActive: 'Active',
    clientUsed: 'Used',
    clientCancelled: 'Cancelled',
    clientPaid: 'Paid',
    clientPending: 'Pending',
    clientViewTicket: 'View ticket',
    clientSection: 'Section',
    clientRow: 'Row',
    clientSeat: 'Seat',
    clientCode: 'Code',
  },
};

type TranslationKeys = keyof typeof translations['es'];

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKeys) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => { },
  t: (key) => translations.en[key] ?? translations.es[key],
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en');

  useEffect(() => {
    const stored = localStorage.getItem('lpticket_lang') as Lang;
    if (stored === 'en' || stored === 'es') setLangState(stored);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('lpticket_lang', l);
  };

  const t = (key: TranslationKeys): string => translations[lang][key] ?? translations.es[key];

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
